import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        "green-dark": "hsl(var(--green-dark))",
        "green-mid": "hsl(var(--green-mid))",
        "green-btn": "hsl(var(--green-btn))",
        "green-bg": "hsl(var(--green-bg))",
        "green-logo-bg": "hsl(var(--green-logo-bg))",
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        cream: "#EBE1D1",
        creamLight: "#F5F0E8",
        creamDeep: "#DDD0BA",
        green: "#41644A",
        darkGreen: "#0D4715",
        orange: "#E8893A",
        orangeDark: "#C97028",
        orangeLight: "#F7D4A8",
        whiteSoft: "#FDFAF6",
        textDark: "#1A2C1C",
        textLight: "#7A8C7C",
        "on-tertiary-fixed": "#261a00",
        "tertiary-fixed": "#ffdfa0",
        "on-primary-container": "#7dbaa9",
        "surface-container-low": "#f4f3f1",
        "on-tertiary-fixed-variant": "#5c4300",
        "primary-container": "#004b3e",
        "on-error-container": "#93000a",
        "surface-container-high": "#e9e8e5",
        surface: "#faf9f6",
        "on-secondary-fixed-variant": "#574500",
        "error-container": "#ffdad6",
        "surface-container": "#efeeeb",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#745c00",
        "on-surface": "#1a1c1a",
        "tertiary-fixed-dim": "#fbbc00",
        "surface-dim": "#dbdad7",
        outline: "#707975",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#0a5043",
        "inverse-on-surface": "#f2f1ee",
        "surface-bright": "#faf9f6",
        "tertiary-container": "#553e00",
        "surface-container-highest": "#e3e2e0",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#95d3c1",
        "on-primary-fixed": "#00201a",
        "secondary-container": "#fed65b",
        "secondary-fixed-dim": "#e9c349",
        "on-primary": "#ffffff",
        "on-surface-variant": "#404945",
        "surface-variant": "#e3e2e0",
        "secondary-fixed": "#ffe088",
        "outline-variant": "#bfc9c4",
        error: "#ba1a1a",
        "inverse-surface": "#2f312f",
        "on-tertiary-container": "#dda500",
        "on-background": "#1a1c1a",
        "inverse-primary": "#95d3c1",
        "on-secondary": "#ffffff",
        "surface-tint": "#2b695a",
        tertiary: "#3a2900",
        "on-secondary-fixed": "#241a00",
        "primary-fixed": "#b0efdd",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },

      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
} satisfies Config;
